### ISSUE TITLE
can u fix it ? 

### ISSUE THREAD

**Issue by PachiMc** [Amatobahn/sea-of-afk#1]
title :D

**Comment by Amatobahn** [comment]
Qt Dependencies in source are fixed and up to date.

**Comment by PachiMc** [comment]
> Qt Dependencies in source are fixed and up to date.

thank you but i get this error on py app.py
  File "app.py", line 49
    def afk(self, afk: bool = False):
tred with python 3 and 2, not sure what is wrong, maybe dependency ?

**Comment by Amatobahn** [comment]
There are two core dependencies for this:
PySide2
pywin32
